CREATE TABLE public.event (
    id integer NOT NULL,
    banner_image_url character varying(255),
    capacity integer,
    category character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    end_date_time timestamp(6) without time zone,
    price numeric(38,2),
    registration_close_at timestamp(6) without time zone,
    registration_open_at timestamp(6) without time zone,
    start_date_time timestamp(6) without time zone,
    status character varying(255),
    title character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    venue character varying(255),
    visibility character varying(255),
    organizer_id integer,
    CONSTRAINT event_category_check CHECK (((category)::text = ANY ((ARRAY['MUSIC'::character varying, 'SPORTS'::character varying, 'TECHNOLOGY'::character varying, 'EDUCATION'::character varying, 'BUSINESS'::character varying, 'WORKSHOP'::character varying, 'ART'::character varying, 'FOOD'::character varying, 'POLITICAL'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT event_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PENDING_APPROVAL'::character varying, 'PUBLISHED'::character varying, 'REGISTRATION_OPEN'::character varying, 'REGISTRATION_CLOSED'::character varying, 'ONGOING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT event_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[])))
);


ALTER TABLE public.event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.event_registration (
    id integer NOT NULL,
    registered_at timestamp(6) without time zone NOT NULL,
    status character varying(255),
    event_id integer,
    user_id integer,
    CONSTRAINT event_registration_status_check CHECK (((status)::text = ANY ((ARRAY['REGISTERED'::character varying, 'CANCELED'::character varying])::text[])))
);


ALTER TABLE public.event_registration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_registration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);





CREATE TABLE public.payment (
    id bigint NOT NULL,
    amount numeric(38,2),
    created_at timestamp(6) without time zone NOT NULL,
    paid_at timestamp(6) without time zone,
    payment_method character varying(255),
    status character varying(255),
    transaction_id character varying(255),
    registration_id integer NOT NULL,
    CONSTRAINT payment_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['UPI'::character varying, 'CREDIT_CARD'::character varying, 'DEBIT_CARD'::character varying, 'NET_BANKING'::character varying, 'PAY_LATER'::character varying])::text[]))),
    CONSTRAINT payment_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);



ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.ticket (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    status character varying(255),
    ticket_number character varying(255),
    registration_id integer,
    CONSTRAINT ticket_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'CHECKED_IN'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.users (
    id integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    is_email_verified boolean,
    name character varying(255),
    password character varying(255),
    role character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ATTENDEE'::character varying, 'ORGANIZER'::character varying, 'ADMIN'::character varying])::text[])))
);



ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.verification_token (
    id bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.verification_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.event
    ADD CONSTRAINT event_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.event_registration
    ADD CONSTRAINT event_registration_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.event_registration
    ADD CONSTRAINT uk4luonmc0xuogbj97rm90k5r8b UNIQUE (user_id, event_id);




ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT uk9lvdv8xuyt431yjmbqd65j6g8 UNIQUE (registration_id);



ALTER TABLE ONLY public.payment
    ADD CONSTRAINT ukgt9akf98nyrqtawemwf8gjij6 UNIQUE (registration_id);


ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT ukp678btf3r9yu6u8aevyb4ff0m UNIQUE (token);



ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT ukq6jibbenp7o9v6tq178xg88hg UNIQUE (user_id);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT verification_token_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.event_registration
    ADD CONSTRAINT fk2ra3ocp6gfw2vbwybbooxxuml FOREIGN KEY (event_id) REFERENCES public.event(id);



ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT fk3asw9wnv76uxu3kr1ekq4i1ld FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.event_registration
    ADD CONSTRAINT fkbg63nw2gjmobd83jhrebr8rx1 FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fkeun91nubadbwh83l1wk4yeuqu FOREIGN KEY (registration_id) REFERENCES public.event_registration(id);



ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkeuomstnwwf41t95o08xjbb5sb FOREIGN KEY (registration_id) REFERENCES public.event_registration(id);



ALTER TABLE ONLY public.event
    ADD CONSTRAINT fkhuu2qgto4g6ktuf87710bfkuq FOREIGN KEY (organizer_id) REFERENCES public.users(id);

